/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HeroBg: typeof import('./src/components/HeroBg.vue')['default']
    HeroBgContent: typeof import('./src/components/HeroBgContent.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCard: typeof import('./src/components/TheCard.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheImageCard: typeof import('./src/components/TheImageCard.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
  }
}
