/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CoolSection: typeof import('./src/components/CoolSection.vue')['default']
    HeroBg: typeof import('./src/components/HeroBg.vue')['default']
    HeroLayout: typeof import('./src/components/HeroLayout.vue')['default']
    HighlyDiversifiedTypography: typeof import('./src/components/HighlyDiversifiedTypography.vue')['default']
    Intro: typeof import('./src/components/Intro.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    Logo: typeof import('./src/components/Logo/index.vue')['default']
    MakeCarousel: typeof import('./src/components/MakeCarousel.vue')['default']
    Page: typeof import('./src/components/Page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCard: typeof import('./src/components/TheCard.vue')['default']
    TheCounter: typeof import('./src/components/TheCounter.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheImageCard: typeof import('./src/components/TheImageCard.vue')['default']
    TheInput: typeof import('./src/components/TheInput.vue')['default']
    WhiteSection: typeof import('./src/components/WhiteSection.vue')['default']
    WhoWeAreTypography: typeof import('./src/components/WhoWeAreTypography.vue')['default']
  }
}
